### ISSUE TITLE
Suggestion to include more practical stuff

### ISSUE THREAD

**Issue by geekyJock8** [aviaryan/learn-for-free#17]
First of all, thank you for doing this @aviaryan.
All of these courses are great!
I was thinking that including more practical courses especially in terms of coding would be great! I could suggest some but I think that you'll provide far better sources than me.

**Comment by aviaryan** [comment]
@geekyJock8 That's a good suggestion. By practical courses, do you mean courses that involve building something? Feel free to send a PR in that case since I can't think of any such courses.

**Comment by geekyJock8** [comment]
Well, I have a few in mind!
Should I add them to the Programming section?

**Comment by aviaryan** [comment]
@geekyJock8 Feel free.

**Comment by aviaryan** [comment]
@dhruvbpatel If they are free, yes.
 I am sure there is already a project for programming books listing otherwise.

**Comment by aviaryan** [comment]
Closing as the purpose of the issue has been fulfilled.
