### ISSUE TITLE
C++ section misplaced in Programming

### ISSUE THREAD

**Issue by geekyJock8** [aviaryan/learn-for-free#27]
I think the C++ section got misplaced in the https://github.com/aviaryan/learn-for-free/blob/master/programming.md

It's placed middle of the Web Development section:

![image](https://user-images.githubusercontent.com/19239291/67192518-5c335480-f411-11e9-8eac-0f8f16d67f71.png)

**Comment by aviaryan** [comment]
If you go by the order in the TOC, C++ should come before Django because of alphabetical sorting. Also, it should be after Web Development since Web Development is goal-oriented (a different section). Perhaps we can do something else to make it more clear.

**Comment by geekyJock8** [comment]
Oh, my bad!
I thought that Django was a subsection of the web development.
Yeah, I agree it's a bit confusing right now!
